language: rust
os: linux
dist: focal
rust:
  - 1.47.0
  - stable
  - beta
  - nightly
env:
  global:
    - RUSTFLAGS='-F warnings'
    - RUST_BACKTRACE=full
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      install: cargo fmt --version || rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - scripts/rustfmt_quote.py --check
    - stage: Check
      name: Clippy
      install: cargo clippy --version || rustup component add clippy
      script: cargo clippy -- --deny warnings
    - stage: Test
      name: Minimum
      rust: 1.45.0
    - stage: Test
      os: osx
    - stage: Test
      os: windows
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
